
spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: micro-service-cloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://132.232.44.33:3366/cloudDB01
    username: root
    password: Admin123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.gengsl.cloud.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mapper/**/*.xml                       # mapper映射文件

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: micro-service-cloud-dept8001 # 自定义服务实例Id
    prefer-ip-address: true     #访问路径可以显示IP地址

# http://192.168.2.100:8001/info优化显示
info:
  app.name: web-microservicecloud-config-dept-config02
  company.name: www.web.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---

server:
  port: 8001
spring:
  profiles: test
  application:
    name: micro-service-cloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://132.232.44.33:3366/cloudDB02
    username: root
    password: Admin123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.gengsl.cloud.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mapper/**/*.xml                       # mapper映射文件

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: micro-service-cloud-dept8001 # 自定义服务实例Id
    prefer-ip-address: true     #访问路径可以显示IP地址

# http://192.168.2.100:8001/info优化显示
info:
  app.name: web-microservicecloud-config-dept-config02
  company.name: www.web.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
